### ISSUE TITLE
회원가입시 입력받은 정보 검증하는 기능 추가

### ISSUE THREAD

**Issue by yejun614** [Sweet-And-Sour/FourB-Backend#15]
## 설명
1. 회원가입을 할 때 지금은 사용자가 입력한 데이터를 무조건 신뢰하고 DB에 정보를 추가하고 있습니다.
2. 입력받은 정보가 올바른지 검증하는 기능을 추가해 주세요.

## TODO
- [ ] 중복 Email 확인
- [ ] Email 형태가 올바른지 확인
- [ ] Username 최소 길이 확인
- [ ] Username 특수 문자 포함여부 확인
- [ ] Password 최소 길이 확인
